### ISSUE TITLE
No cellular signal bars on ipx status bar on home screen 

### ISSUE THREAD

**Issue by A13X23** [duraidabdul/Neptune#10]
This is what I mean, i the top right it only says lte and battery, like here: https://imgur.com/gallery/6S3LrYv

**Comment by duraidabdul** [comment]
Interesting. Not sure why that happens, as it is the native status bar with no modifications. What other tweaks do you use?

**Comment by A13X23** [comment]
Turns out the issue was because I disabled the carrier name with springplus, so it also disabled the cellular signal for some reason lol

**Comment by duraidabdul** [comment]
Cool, glad you managed to get it fixed :)
