### ISSUE TITLE
Home bar not appearing is broken

### ISSUE THREAD

**Issue by ryannair05** [duraidabdul/Neptune#101]
**Describe the bug**
The home bar is still visible while Homebar is set to not enable

**Type**
[UI/Usability]

**Expected behavior**
The homebar is expected to not be shown if that option is exercised in settings. I did respring if you need to make sure.

**Screenshots**
I can send some later if needed

**Information**
 - Device: [iPhone 7 Plus]
 - iOS Version:  iOS 12.1.1 (16C50)]
 - Tweak Version: [Beta 8]

**Comment by duraidabdul** [comment]
Fixed in latest build :)
