### ISSUE TITLE
Netflix app does not load videos 

### ISSUE THREAD

**Issue by rodrigmatrix** [duraidabdul/Neptune#11]
**Describe the bug**
Netflix app does not load videos.

**Type**
Bug

**Steps to Reproduce**
1. Go to netflix
2. Play a show/movie
3. Get stuck on a infinite loading

**Information**
 - Device: iPhone 6s
 - iOS Version: [e.g. iOS 12.1.2 (16C104)]
 - Tweak Version: [e.g. 1.0 beta 2]

**Additional information**
When I deleted the tweak the app works.

**Comment by michael50310** [comment]
Actually this issue is caused by jailbreak itself. 
In my case after using rootlessJB to jailbreak, my Netflix won’t play any video either.

**Comment by rodrigmatrix** [comment]
> Actually this issue is caused by jailbreak itself.
> In my case after using rootlessJB to jailbreak, my Netflix won’t play any video either.

Ty😀
