### ISSUE TITLE
Hotspot Bug

### ISSUE THREAD

**Issue by tweaktester505** [duraidabdul/Neptune#115]
Unable to enable personal hotspot. Could be caused by the 12.2 stuff added to Neptune.

**Comment by tweaktester505** [comment]
I’m able to enable but when I try to connect a device to the hotspot it fails. I do have unlimited hotspot through AT&T.

**Comment by duraidabdul** [comment]
This has nothing to do with Neptune, it doesn’t mess with any of that stuff.

**Comment by tweaktester505** [comment]
Your right, thanks you for letting me know. Tried rejailbreaking and It got fixed.😊
