### ISSUE TITLE
Crashed springboard 

### ISSUE THREAD

**Issue by Salsaboi751** [duraidabdul/Neptune#130]
It keeps crashing during springboard and the crash reported has said that it is Neptune’s tweak causing this please fix this the device I’m running the tweak is iPhone 8 version 13.3 and running via checkra1n 
![04880CF8-DD49-4DD1-9FE0-66BC02000A10](https://user-images.githubusercontent.com/61308023/75011990-a02d7900-5446-11ea-8ac0-b2b88be081a5.jpeg)

**Comment by duraidabdul** [comment]
Neptune only supports iOS 12.
