### ISSUE TITLE
Spotlight search causing Springboard to hang

### ISSUE THREAD

**Issue by TheShadyRelapse** [duraidabdul/Neptune#15]
**Describe the bug**
It disables the ability to swipe left and right on the home screen

**Type**
Glitch

**Steps to Reproduce**
1. Swipe down for the Spotlight Search
2. Close Spotlight Search 
3. Try to swipe left or right

**Expected behavior**
Everything to be normal and able to swipe left and right.
**Screenshots**

**Information**
 - Device: iPhone SE
 - iOS Version: iOS 12.1.1
 - Tweak Version: 1.0 beta 2

**Additional information**

**Comment by duraidabdul** [comment]
Thanks for the report! This issue is fixed in beta 4 (not released quite yet, expect it soon).

**Comment by duraidabdul** [comment]
This is fixed in beta 4.
