### ISSUE TITLE
[Request] Revert the screenshot buttons

### ISSUE THREAD

**Issue by deyanm** [duraidabdul/Neptune#2]
Maybe it will be better to disable the screenshot action from X design, and keep the original one. Also, as other people pointed on reddit, we could keep the original status bar.

Tested device: iPhone 6S, iOS 12.1

**Comment by joaodforce** [comment]
I actually like this behavior, it’s better to do one handed. However options would be great. Maybe a preferences panel gets added in the future

**Comment by duraidabdul** [comment]
Fixed now! @joaodforce a preference panel for this will be added in the future :)
