### ISSUE TITLE
Can you make a version without the modern status bar?

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#21]

**Comment by PkmnTrnrGary** [comment]
+1 to this feature request.

**Comment by duraidabdul** [comment]
Will be done when preferences are added in a future version.

**Comment by carsonCN** [comment]
Actually I think this is a great feature with more modern and taller status bar and sure it would be the next trending . I noticed that some common-used app like WeChat Alipay zhihu weibo all has been  adapted by developer. Can you add Jike (即刻App） for
it? Thank you a lot! Thank you for your great  job! Kind regards.
