### ISSUE TITLE
Redundant flashlight/camera buttons

### ISSUE THREAD

**Issue by Thaopt191** [duraidabdul/Neptune#22]
**Describe the bug**
The flashlight and camera button also display in notification center not just on lockscreen

**Type**
UI/Usability

**Steps to Reproduce**
Pull down the NC while unlocked

**Expected behavior**
Remove two buttons or just change its position 

**Information**
 - Device:  iPhone 7+
 - iOS Version: iOS 12.1.1 b3
 - Tweak Version: 1.0 beta 3

**Comment by poppychan** [comment]
Thats what its supposed to do. Its like that on the newer iPhones as well
