### ISSUE TITLE
Apps Flashing 

### ISSUE THREAD

**Issue by PkmnTrnrGary** [duraidabdul/Neptune#23]
When using gestures to dismiss apps or pull up the app switcher, apps flash sporadically, then stop flashing once loaded into frame. 

Device: i6s+

**Comment by PkmnTrnrGary** [comment]
This appears upon further testing to be related to the status bar changing when an app is attempting to load in, be it in the switcher or in the foreground. Once an app loads in the original status bar, they no longer flash.

**Comment by duraidabdul** [comment]
Please send a screen recording of the issue. Thanks!

**Comment by PkmnTrnrGary** [comment]
Hey there Duraidabdul, after I re-jail broke I was unable to reproduce this issue. It appears that it was either a bug related to the jailbreak itself, or some other external cause. I think you can close this issue. Thank you for your hard work!
