### ISSUE TITLE
The icon looks disproportionate

### ISSUE THREAD

**Issue by dxchien** [duraidabdul/Neptune#27]
Battery icon looks bigger than others
![neptune](https://user-images.githubusercontent.com/4531494/52630698-82523d80-2eef-11e9-98c1-088d93972faf.png)

**Information**
 - Device: iPhone 7
 - iOS Version: 12.1.1
 - Tweak Version: 1.0 beta 4

**Comment by duraidabdul** [comment]
I believe that screenshot on the iPhone X was taken on a previous version of iOS. On iOS 12, they should both be identical.
