### ISSUE TITLE
Search Textbox override Time

### ISSUE THREAD

**Issue by dxchien** [duraidabdul/Neptune#28]
**Describe the bug**
Search Textbox override Time

**Type**
UI

**Steps to Reproduce**
1. Swipe right from LS
2. See error

**Expected behavior**
Search Textbox override Time

**Screenshots**
![image](https://user-images.githubusercontent.com/4531494/52686970-87ac9800-2f82-11e9-8ea2-946437cdf05d.png)

**Information**
 - Device: iPhone 7
 - iOS Version: 12.1.1
 - Tweak Version: 1.0 beta 4

**Comment by duraidabdul** [comment]
Fixed in beta 5 :)
