### ISSUE TITLE
CC Bug

### ISSUE THREAD

**Issue by skrypious** [duraidabdul/Neptune#29]
if you enable or disable the wifi / mobile network several times, the system will hang and crash

**Comment by duraidabdul** [comment]
Please attatch a video reproducing the issue.

**Comment by skrypious** [comment]
> Please attatch a video reproducing the issue.

https://www.youtube.com/watch?v=XHsSpTSDbYQ&feature=youtu.be
This error does not appear every time. Tested on iPhone 7, iOS 12.1.1 b3, Neptune 1.0 beta 4

**Comment by duraidabdul** [comment]
Thanks for the screen recording! I’m currently unable to reproduce this issue, but I will hopefully find a fix if I run into it.
