### ISSUE TITLE
May be reduce the size of the status bar for iphone SE

### ISSUE THREAD

**Issue by joelmuppidi** [duraidabdul/Neptune#31]
The status bar size too big and because of it the icons get crumpled into each other a bit and the dock is disproportionate for SE like devices.   

thanks for the tweak its great by the way.

**Comment by vildzi** [comment]
Its a known bug and will probably be resolved soon

**Comment by duraidabdul** [comment]
The status bar is fixed in the upcoming release. I will address the dock issue for the iPhone SE in another release, it may take a little while longer.
