### ISSUE TITLE
1-2 second delaying to lock the screen after pressing the power button

### ISSUE THREAD

**Issue by habarent** [duraidabdul/Neptune#32]
Not a major issue, but I've noticed that when I press the power button, there's a bit of a delay before the phone locks itself. Also when I'm using the phone it seems to get quite hot when I have the tweak installed.
No issues other than that, and really impressive work!

iPhone 6s
iOS 12.1.2
Neptune Beta 4

**Comment by duraidabdul** [comment]
Shouldn't happen on the latest beta
