### ISSUE TITLE
iBooks crash after first launch

### ISSUE THREAD

**Issue by rodrigmatrix** [duraidabdul/Neptune#33]
**Describe the bug**
iBooks crash after opening for the first time when unlocked
**Information**
 - Device: [e.g. iPhone 6s]
 - iOS Version: [e.g. iOS 12.1.2 (16C104)]
 - Tweak Version: [e.g. 1.0 beta 3]

**Comment by duraidabdul** [comment]
This should be fixed by updating to today's version of rootlessJB3. Please comment if you run into it again.
