### ISSUE TITLE
Add Large Keyboard style iPhone x

### ISSUE THREAD

**Issue by jr0driguezv** [duraidabdul/Neptune#36]
Hello, I like this, could you add the style of the iPhone X keyboard too? . Another thing the status bar does not show as iphone X when it is inside the applications

**Comment by duraidabdul** [comment]
This is added in beta 5

**Comment by jr0driguezv** [comment]
Thanks, I look forward to this function, I look forward to testing it with the Tweak "BarMoji" will it add support for this?

**Comment by jr0driguezv** [comment]
Hello again, I tested your Beta 5 and the keyboard style of the iPhone X does not work, I have iPhone 7 Plus and the keyboard is normal, it does not have the appearance of the iPhone X :(

**Comment by jr0driguezv** [comment]
It worked, for some strange reason it did not work at the beginning. Enter settings and turn off the switch for options:

- Home Indicator (Display Within Apps)
- Keyboard (Enable Buttom Bar)

There is a respring this has sent me to Safe Mode. Then I turned on both switches and now if the keyboard works style iPhone X. 😃🙂 Thanks
