### ISSUE TITLE
iPhone 8 tester

### ISSUE THREAD

**Issue by GODLIKE5** [duraidabdul/Neptune#42]
Hi! I'm on iOS 12.1.1 with rootless JB and 1 the lockscreen toggles don't function at all and the other issue I saw was that the header that looks like the iPhone X disappears when entering another app. Btw I have enable system wide.

**Comment by hieurock** [comment]
Have you tried to 3D Touch the lock screen toggles? It’s working fine on my 8 Plus. I am also having your same issue with the system wide modern status bar.

**Comment by GODLIKE5** [comment]
Yea I have.. I also tried switching the sensitivity for the 3D touch but nothing.


Edit: I snooped thru the tweaks folder and changed some permissions around. I got the system wide bar working now

Link of proof: https://imgur.com/a/H1zFunv

**Comment by duraidabdul** [comment]
Have you changed the resolution of your device by any chance? (Eg upscale or changing system files)

**Comment by lhason** [comment]
I found that system wide status bar only works in system app and clock app. Godlike5’s work sounds impressive, how did u do that? so u opened up the permission to all apps? thanks man

**Comment by GODLIKE5** [comment]
Duraidabdul no I have not. Ihason. I opened up filza and navigated to the tweaks folder>>Neptune>>i icon>>make sure it says this>>make sure you click Sticky>>0755.

Link: https://imgur.com/a/D38unTg

**Comment by lhason** [comment]
Godlike5 sorry for the late reply. Yea I just checked and I have the same settings as yours, 0755. Other settings are the same as well. I’ve been figuring out this problem for the whole week lol was trying to look for HomeGesture Full deb file but I could not. :( peace

**Comment by GODLIKE5** [comment]
I'll send u my files, got email?

**Comment by lhason** [comment]
lhasn7@gmail.com cheers bro, appreciate it
