### ISSUE TITLE
Disable X Gesture when using keyboard

### ISSUE THREAD

**Issue by LK1105** [duraidabdul/Neptune#43]
It is easy to trigger the gesture when I using the keyboard. Hope developer can add an option to disable X gesture when using the keyboard. If this feature is planning to add. It will improve experience to use this tweak! Thank you!

**Comment by jr0driguezv** [comment]
I would like this option too

**Comment by duraidabdul** [comment]
There is now an option to use the taller iPhone X keyboard to fix this issue
