### ISSUE TITLE
[Request][Issue] Picture in Picture making Spotify not open

### ISSUE THREAD

**Issue by A13X23** [duraidabdul/Neptune#47]
Yesterday before I got this tweak I got picture in picture, but then like unc0ver used to do before substrate, Spotify wouldn’t open then(Instagram does though for some reason). I like having picture in picture but please make a version similar to how there used to be versions with no homebar, but without picture in picture. Thanks for the hard work!

**Comment by A13X23** [comment]
Kinda a typo, but basically I deleted pip yesterday and Spotify worked again. Now though with Neptune the issue is back is what I mean

**Comment by kekrajb** [comment]
Same for me. Spotify not open

**Comment by duraidabdul** [comment]
Duplicate of #46
