### ISSUE TITLE
I do not see the icons of the lamp and the camera on the lock screen.

### ISSUE THREAD

**Issue by jacman23** [duraidabdul/Neptune#49]
**Describe the bug**
I do not see the icons of the lamp and the camera on the lock screen.

**Type**
UI/Usability

**Steps to Reproduce**
I perform the installation with filza and restart.

**Expected behavior**
I do not see the icons of the lamp and the camera on the lock screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/41385058/53256024-8cf99900-368c-11e9-8b8f-52841c3df6cc.png)

**Information**
 - Device: [iPhone 6]
 - iOS Version: [ iOS 12.1.2 (16C104)]
 - Tweak Version: [Beta 5 ]

**Additional information**
Add any other information about the problem here.

**Comment by duraidabdul** [comment]
This is likely because you are using a conflicting tweak that removes them to modify your lock screen.
