### ISSUE TITLE
Problems on iPhone 8 Plus

### ISSUE THREAD

**Issue by oc-tk** [duraidabdul/Neptune#5]
No lock icon on lockscreen, no buttons, everything on lockscreen is shifted right by big value.
Not compatible with DockXI (Dock is misaligned with icons - statusbar space is a problem).

Sometimes it crashes. Hard to reproduce.

 - Device: iPhone 8+
 - iOS Version: 12.1.2

**Comment by duraidabdul** [comment]
Dock is fixed, lock screen toggles are in the works.
