### ISSUE TITLE
The space between the home indicator and the application is not correct

### ISSUE THREAD

**Issue by jr0driguezv** [duraidabdul/Neptune#50]
**Describe the bug**
The space between the home indicator and the application is not correct

**Type**
Ui

**Steps to Reproduce**
 
![image](https://user-images.githubusercontent.com/34715057/53262395-d823a400-36ac-11e9-8528-cf18c647393f.png)

**Expected behavior**
Have the space as shown on the iPhone X. The globe and the microphone should have a little more space.

**Screenshots**

This is how it should look properly

![image](https://user-images.githubusercontent.com/34715057/53262465-00ab9e00-36ad-11e9-8c47-c361eedd2b20.png)

**Information**
 - Device: iPhone 7 Plus
 - iOS Version: 12.1.2 (16C104)
 - Tweak Version: 1.0 beta 5

**Comment by duraidabdul** [comment]
Not an issue. Reason it’s a smaller space is so that it uses less screen space :)

**Comment by iperfectnb** [comment]
Kindly correct this for users who don’t mind extra space usage,this really annoys in 3rd party applications. 🙏
