### ISSUE TITLE
Neptune cause spotify app freeze & clock not aligning correctly 

### ISSUE THREAD

**Issue by amirhossein1371** [duraidabdul/Neptune#51]
Hi in this update spotify app freeze on launch and a few seconds later app crashes.
Also clock not aligning in up left screen.
Please fix it thanks

**Comment by ghost** [comment]
Use the spotify fixed version. And for me the clock is aligned correctly can you maybe attach a screenshot?

**Comment by amirhossein1371** [comment]
Thanks for replay.clock problem fixed after installing Cydia
