### ISSUE TITLE
Installing Uncover Cydia

### ISSUE THREAD

**Issue by hackerdr** [duraidabdul/Neptune#52]
How can I install this with cydia ? Where is the repo source ? I have tried to install with geofilza but it says command not found.

**Comment by teelekkung** [comment]
Duplicate of 45#

**Comment by addtheryan** [comment]
Yes same on me
bash: Filza: command not found

**Comment by teelekkung** [comment]
For me work well after use filza tweak in cydia not geo filza and download deb file from pc then transfer to my phone

**Comment by kekrajb** [comment]
If you want install Neptune with Cydia: repo.conorthedev.com

**Comment by addtheryan** [comment]
Just use @kekrajb repo link . It work
Thanks btw issue closed
