### ISSUE TITLE
Can't screenshot on iPad

### ISSUE THREAD

**Issue by FlintyLemming** [duraidabdul/Neptune#6]
**Describe the bug**
Can't screenshot on iPad. I've tried power button+volume like iPhone but doesn't work.

**Type**
Bug

**Information**
 - Device: iPad Pro 10.5
 - iOS Version: 12.1.2 (16B92)
 - Tweak Version: 1.0 beta 1

**Comment by duraidabdul** [comment]
I'm looking into a fix for the screenshot issue, but out of curiosity, why would you use this tweak on iPad? iPad already has FluidUI enabled by default.

**Comment by duraidabdul** [comment]
Duplicate of #2

**Comment by A13X23** [comment]
Try power-volume up
