### ISSUE TITLE
Add FaceID padlock

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#63]
Hey could you add FaceID padlock to the lock screen

This tweak https://github.com/SniperGER/ProudLock does that but it's broken on iOS 12.

**Comment by hieurock** [comment]
I would like this as well. I like to enable Raise to Wake so that when I raise my phone while my thumb is resting on Touch ID, I can just swipe to unlock. The padlock icon would be satisfying.

**Comment by duraidabdul** [comment]
Duplicate of #98
