### ISSUE TITLE
3D Touch App Switcher

### ISSUE THREAD

**Issue by PWittix** [duraidabdul/Neptune#71]
Neptune b6 removes the stock shortcut of 3d touching the left side of the screen to switch between the previous app and/or bring up the app switcher. 

This affects iPhone 7+ iOS 12.1.1b3.

**Comment by hakiimmislam** [comment]
Because on iPhone X there is no function for 3d touch shortcut on the left side of the screen. Neptune replicates the iPhone X gesture.
