### ISSUE TITLE
Inconsistent status bar mode

### ISSUE THREAD

**Issue by OfficiallySp** [duraidabdul/Neptune#77]
When using the Modern Large status bar setting In some apps like Facebook messenger and safari the status bar behaves as normal. However in some apps like twitter and instagram. It uses the Modern Recommended setting

Device - iPhone SE
Version - Beta 6
iOS - 12.1.1

**Comment by duraidabdul** [comment]
Yup, that’s because using the tall status bar causes unexpected behavior in many apps. There’s a whitelist for apps which includes Apple apps and some other ones that have been tested to be stable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
