### ISSUE TITLE
Neptune settings are unavailable

### ISSUE THREAD

**Issue by amandamana** [duraidabdul/Neptune#78]
**Describe the bug**
Neptune settings are unavailable

**Type**
~~UI bug or~~ missing dependency

**Steps to Reproduce**
Install from https://tweakportal.yourepo.com including respring by Cydia, respring (again to be sure), go to Settings app, scroll through or search for Neptune settings...nothing.

**Expected behavior**
I understand there should options for this tweak, accessible from Settings

**Information**
 - Device: iPhone SE
 - iOS Version: iOS 12.1.1b3
 - Tweak Version: beta 6

**EDIT:** looks like package meta-information needs to include a PreferenceLoader dependency. Manually installing PreferenceLoader from BigBoss fixes this issue.

**Comment by hieurock** [comment]
I had this issue as well, but I resolved it by installing another tweak that had settings.

**Comment by hieurock** [comment]
Have you tried installing another tweak? I had this problem but I could see it in the setting again after I downloaded another tweak.

**Comment by ghost** [comment]
You're probably using an outdated version download the tweak from this repository : https://repo.conorthedev.com/

**Comment by amandamana** [comment]
tweakportal repo was [recommended by DuraidAbdul](https://www.reddit.com/r/jailbreak/comments/ax4130/update_neptune_for_ios_12_beta_6/) and described as "beta 6" both by DuraidAbdul and within the repo. The version number is "1.0.0-224". For comparison, the version number on conorthedev's repo is obstensibly "1.0.0-22" and I have not tried installing it.

**Comment by duraidabdul** [comment]
Thanks for the report, I’ll fix that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duraidabdul** [comment]
Make sure you have PreferenceLoader installed!
