### ISSUE TITLE
iMessage Voice Messages Crashes

### ISSUE THREAD

**Issue by hieurock** [duraidabdul/Neptune#79]
The messages app crashes whenever I try to record a voice message. 

Type: Crash

Steps to Reproduce
1. Compose an iMessage to another iOS user
2. Press on the microphone in the text box

https://youtu.be/7ZDvPu7nY-o

Information

Device: iPhone 8 Plus
iOS Version: 12.1.2 16C101
Tweak Version: 1.0 beta 6

**Comment by amandamana** [comment]
I can reproduce this on my SE running 12.1.1b3

**Comment by ghost** [comment]
Same issue.

**Comment by aletebon** [comment]
why do you think it can be connected with the tweak? just do a little 'research to understand that the problem goes back upstream ... https://github.com/pwn20wndstuff/Undecimus/issues/604

**Comment by hieurock** [comment]
Well, I’m sorry. Jailbreaking is relatively new to me.

**Comment by duraidabdul** [comment]
No reason to be sorry, thanks trying to help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
