### ISSUE TITLE
Fix tab bar height in applications

### ISSUE THREAD

**Issue by xwbchn** [duraidabdul/Neptune#8]
Modify the /var/containers/shared/systemgroup/systemgroup.com.apple.mobilegestaltcache/library/caches/com.apple.mobilegestalt.plist
find root-cacheextra-opeik/9e8iqwmszejbpzng-ArtworkDeviceSubType,then modify this to 2436，Then It can be fixed after respring。
This is the method used to turn on iphonex native gestures，I found it can be used to fix this problem。

**Comment by xwbchn** [comment]
My post from chinese forum，All models can use this method to fix this bug。
https://bbs.feng.com/read-htm-tid-12034261.html

**Comment by duraidabdul** [comment]
Yes this can be used to fix the issue, but it also breaks the navigation bars (due to an attempt at making space for large status bars) for many apps, and also breaks many games. I'll be looking into fixing the tab bar when rootlessJB supports applications other than Springboard.

**Comment by duraidabdul** [comment]
Check out beta 5 :) It fixes this issue for most apps

**Comment by xwbchn** [comment]
thanks but i dont like to use deb file,i will post this to chinese forum,Thank you for your effort！

**Comment by jr0driguezv** [comment]
@duraidabdul  The space is not shown correctly even in beta 5

**Comment by PkmnTrnrGary** [comment]
I can confirm this bug is also still present on my 6S+. The homebar overlaps content on the bottom of apps instead of extending the gray area upward behind the homebar.
