### ISSUE TITLE
Modern statusbar lingers after closing CC

### ISSUE THREAD

**Issue by sie-sh** [duraidabdul/Neptune#80]
I turned off the built in statusbar and recreated it in movable9 because I didn’t like thr extra height it had. When I close CC, the Modern profile shows for a few seconds before disappearing and returning to normal.

**Comment by duraidabdul** [comment]
You can use the recommended status bar option in Settings for the modern style that isn’t tall

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
