### ISSUE TITLE
Screenshot not working

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#82]
Can't take screenshot with home+power and power+volume down

**Comment by cichowlasp** [comment]
Power + volume up work on my 6s

**Comment by duraidabdul** [comment]
Power + volume up is the combination for screenshots

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
yeah this should be only with the « new combinations » toggle activated (it should even be volume down not up but alright) so when using the normal toggles the screenshot should be home + power button

**Comment by duraidabdul** [comment]
Power+home for screenshot is currently disabled until I can make it work without bugs.
