### ISSUE TITLE
Overheating and battery drain

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#85]
With Neptune my phone is overheating and I’m having a battery drain.

**Comment by duraidabdul** [comment]
It's highly unlikely that this is caused by Neptune. Neptune doesn't add any heavy features. What other tweaks do you have installed?

**Comment by ghost** [comment]
7-zip (POSIX): 16.02-1
AppList: 1.5.14
APT (apt-key): 1.4.8-3
APT 1.4 Strict (libapt-pkg): 1.4.8-4
APT Command Line: 1:0-2
APT Strict (lib): 1.4.8-7
APT Strict: 1.4.8-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 4.4.23-2
bzip2: 1.0.6-1
CA Certs: 0.0.1-1
Cephei: 1.12
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cydia Installer: 1.1.32~b12
Cydia Substrate: 0.9.7031
Cydia Translations: 1.1.32~b1
DarkKeysXII: 1.0.1
Darwin Tools: 1-6
Debian Packager: 1.18.25-9
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Essential: 0-1
file: 5.35-2
Filza File Manager: 3.6.4
Find Utilities: 4.6.0-1
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HomeGesture: 2.1.4
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.7.1
iOS Firmware: 12.1
iPhone Firmware (/sbin): 0-1
Jellyfish: 1.0.2
KSBA: 1.3.5-1
LeaveMeAlone: 2.0.0
LetMeBlock: 0.0.1
libcolorpicker: 1.6-1
libCSColorPicker: 0.7.9
libCSPreferences: 1.0.6
libidn2: 6.1.2-1
libnepeta: 0.1.0
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSparkAppList: 1.0.1-1
libswift4: 4.2.1-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
Locale Profiles in UTF-8: 1.0-1
LocalIAPStore: 1.4-2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Milkshake: 1.6
Nettle: 3.4-2
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm 2 (iOS 7 – 11): 2.0
Notifica: 0.1.10
OpenSSL 1.0 Libraries: 1.0.2q-1
p11-kit: 0.23.12-1
PhotoSize: 1.0
PreferenceLoader: 2.2.3-3
Profile Directory: 0-1
readline: 7.0.5-2
RealCC: 1.0.1
ReProvision: 0.4.1
RocketBootstrap: 1.0.6
sed: 4.5-1
shell-cmds: 118-8
Signing Certificate: 0.0.1
SnowBoard: 1.1.4
Substrate Safe Mode: 0.9.6001.1
system-cmds: 790.30.1-2
Tabsa: 1.0
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4~b2
UIKit Tools: 1.1.13-5
Unc0ver Jailbreak Resources: 1.0~b6
unrar: 5.6.4-1
unzip: 6.0-1
VideoHUD: 2.3
WhatAboutThis: 1.0
XZ Utils: 5.2.4-4
zip: 2.32-1

It seems likely to be Neptune because whenever I install it my phone over heat and battery drain, with homegesture I don’t have this problem

**Comment by duraidabdul** [comment]
Take a look at your other tweaks. Neptune has been tested for efficiency and performance, and does not add any heavy functionality to the system.
