### ISSUE TITLE
Disable Swipe Gesture on Older Devices

### ISSUE THREAD

**Issue by PWittix** [duraidabdul/Neptune#86]
Would it be posible to add an option to disable the “swipe up to go home” on  devices iPhone 8 and under. 
 I am on iPhone 7+ and love the lockscreen and status bar, but the swipe up gesture is redundant and gets in the way sometimes.  Alternatively, is there a standalone status bar tweak and a lockscreen tweak that could achieve the same functionality?

**Comment by duraidabdul** [comment]
Not currently the plan but I may add this in the future.
