### ISSUE TITLE
disable hardware button cause default hardware button dont work

### ISSUE THREAD

**Issue by toptabi** [duraidabdul/Neptune#87]
hi, there is small problem, when i disable hardware button in setting i cant use default take screenshot button (home+lock), beta 5 dont have this problem, your tweak still great :D

**Comment by ghost** [comment]
Same

**Comment by kefche20** [comment]
I have the same issue, I cannot screenshot the old way, only power+volup

**Comment by marco2012** [comment]
Same issue on beta 7.
