### ISSUE TITLE
"Modern" status bar showing in apps. 

### ISSUE THREAD

**Issue by lanetrain666** [duraidabdul/Neptune#89]
**Describe the bug**
In certain apps like Twitter, modern status bar (with date) shows instead of big status bar. 

**Type**
UI

**Steps to Reproduce**
1. Go to twitter/ 

**Expected behavior**
should stay the same 

**Information**
 - Device: iPhone 7]
 - iOS Version:  iOS 12.1.1 
 - Tweak Version: beta 6

**Additional information**
Add any other information about the problem here.

**Comment by duraidabdul** [comment]
The large status bar breaks the twitter app on pre iPhone X devices, so its disabled in twitter.
